version: '3'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-carpooly}
      PGDATA: /data/postgres
    volumes:
      - data:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres

  carpooly-backend:
    build: ./spring-final-project-server
    container_name: carpooly-backend
    environment:
      - DB_SERVER=carpooly
    ports:
      - 8080:8080
    links:
      - postgres

volumes:
  data:

networks:
  postgres:
    driver: bridge