# Jenkins Master
db:
  image: blacklabelops/hsqldb
  container_name: hsqldb
  ports:
   - "9001:9001"
  volumes:
    - /opt/database
  env_file:
    - docker-compose.env
  labels:
    com.blacklabelops.description: "HSQL Development System"
    com.blacklabelops.service: "hsqldb-server"

carpooly-backend:
  build: ./spring-final-project-server
  container_name: carpooly-backend
  environment:
    - DB_SERVER=carpooly
  ports:
    - 8080:8080
  links:
    - db